### ISSUE TITLE
Ultra hard mode?

### ISSUE THREAD

**Issue by gwstaten** [alex1770/wordle#4]
This code is amazing and has been very customizable to get a lot of data regarding starting words for multiple word sets, however, some sites require (or just some players like to play) in "ultra hard" mode, which, unlike regular hard mode, requires the user to also move yellows, and to not include any previous gray letters, I have been looking through the code to try to modify it to do this and I know it has something to do with the okhard function, but am not sure how to modify it for this purpose.
Any help or guidance you can give would be greatly appreciated!

**Comment by alex1770** [comment]
Hi gwstaten. Thank you for your kind words. You are right, morally you just have to alter okhard() to return sc[j][i]==s, which enforces that new guesses are compatible with previous colour scores, but to make that work you also need to pre-calculate colour score values (fill the table sc[][]) for guess words as well as hidden words. Anyway, I added an option -U to do this in the last commit. I hope it's the behaviour you expected.

**Comment by alex1770** [comment]
"Ultra hard" mode implemented.
