### ISSUE TITLE
Different word length

### ISSUE THREAD

**Issue by 841** [alex1770/wordle#6]
I'm in need for the optimal strategy for a variant with 6 letter words instead of 5.

Can you modify the code?

I guess "Marine" and "Nature" are sweet for starting words.

A few words have 4 single letter, such as "assess".

**Comment by alex1770** [comment]
Hi, thanks for the suggestion, but sorry, the way the program is written that would be quite a big change and I don't really have time to do this. I wish you well with your 6 letter Wordle.
