### ISSUE TITLE
tarse.hard.nyt20230701.tree error?

### ISSUE THREAD

**Issue by squeakbat** [alex1770/wordle#8]
Hi!

In tarse.hard.nyt20230701.tree, the guess after "tarse BGBBY1" is "pagle".  Isn't that not allowed in hard mode?  That final e should be a G not a Y.  I actually never played hard mode.  I'm just basing it on the description "any revealed hints must be used in subsequent guesses".

I was trying to figure out why you have a hard mode solution for the new 2023 word lists, while my code doesn't (about 6 to 13 words have no solution in 6 guesses, depending on optimization goal).

By the way, I also have a covid stats project as well as a wordle solver.  I guess what else can one do in a pandemic. :)

**Comment by alex1770** [comment]
Hi Ellen, thanks for the question.

As I understand it, the hard mode rules are (i) Any past green must be maintained (letters in green positions must stay there) and (ii) If a letter got a positive response (i.e., yellow or green) 'n' times in a past guess then your guess must include at least 'n' occurrences of that letter.

So for example, if the guess SERVE gets the response BYBBG, then in hard mode, subsequent guesses must include at least two 'E's, including one at the end, but there is no restriction on where the second 'E' goes. And your next guess can include 'S', 'R' or 'V' if you want. (In hard mode, it's always legal to repeat your last guess, even though you know it's wrong.)

In your example of TARSE BGBBY, then subsequent guess must have an 'A' in second position and at least one 'E' somewhere, so PAGLE is legal.

You could certainly imagine a ruleset where each guess has to be a possible correct answer, and this would be a natural thing to do, but it doesn't correspond to the official hard mode rules. (You can get this behaviour with the -U option if you are using the wordle program: 'U' for 'Ultrahard'.)

**Comment by squeakbat** [comment]
Thanks for replying!

I guess it's academic at this point, but do you know of an authoritative description of all the rules?  I literally cannot find an nytimes source that describes hard mode in a precise way.  These are the three I could find:

In-game settings: Any revealed hints must be used in subsequent guesses

Tips and tricks: Once players have found a correct letter in a word — yellow or green — those letters must be used in their subsequent guesses

Glossary: An optional mode in which all found letters must be used in later tries

**Comment by alex1770** [comment]
I couldn't find anything precise either. It's a bit bizarre, but I suppose they don't want to scare people off by making it sound too mathematical.

**Comment by squeakbat** [comment]
Yeah.  It's actually more complicated then "next guess must satisfy previous clues".  Anyways.  Thank you very much for answering.  I'll close this incident now.
